agent_name = "from-cli"
agent_type = "my-type"
#secret_key = "<secret>"
secret_path = "./secrets/secrets.txt"
command = "my-command"
command_args = ["arg1", "arg2"]

[env_overrides]
ENV1 = "value1"
ENV2 = "value2"

[[tunnels]]
name = "YesheyTunnel"
proto = "both"
port_count = 2
local = 25565

special_lan = true