agent_name = "web3MC"
secret_path = "./secrets/secret_syncthing_playitcli.txt"
command = "./bin/linux/syncthing/syncthing"
command_args = [ "--home", "./syncthing_config", "--gui-apikey=3kyNtqsFxfgYuRJU94lz", "--no-default-folder", "--no-browser", "--gui-address=0.0.0.0:23840",]
[[tunnels]]
name = "YesheyTunnel"
proto = "tcp"
port_count = 1
local = 23840
special_lan = true

