agent_name = "web3MC"
secret_path = "./secrets/secret_syncthing_playitcli.txt"
command = "./bin/windows/syncthing/syncthing.exe"
command_args = [ "--home", "./syncthing_config", "--gui-apikey=tOGFgTtkLAo7BNlrC6jT", "--no-default-folder", "--no-browser", "--gui-address=0.0.0.0:23840",]
[[tunnels]]
name = "YesheyTunnel"
proto = "tcp"
port_count = 1
local = 23840
special_lan = true

