agent_name = "web3MCAgent2"
#agent_type = "my-type"
#secret_key = "<secret>"
secret_path = "./../../secrets/secret_main_playitcli.txt"
command = "java"
command_args = ["-Xmx1524M", "-Xmx11G", "-XX:+UseG1GC", "-XX:+ParallelRefProcEnabled", "-XX:MaxGCPauseMillis=200", "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableExplicitGC", "-XX:+AlwaysPreTouch", "-XX:G1NewSizePercent=30", "-XX:G1MaxNewSizePercent=40", "-XX:G1HeapRegionSize=8M", "-XX:G1ReservePercent=20", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=4", "-XX:InitiatingHeapOccupancyPercent=15", "-XX:G1MixedGCLiveThresholdPercent=90", "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:SurvivorRatio=32", "-XX:+PerfDisableSharedMem", "-XX:MaxTenuringThreshold=1", "-Dusing.aikars.flags=https://mcflags.emc.gs", "-Daikars.new.flags=true", "-jar", "./fabric-server-launch.jar", "nogui"] # 9e0a3886-8b6d-403a-9755-1d67987eb440=192.168.1.20:25565
# java -Xmx1024M -Xms1024M -jar server.jar nogui

#[env_overrides]
#ENV1 = "value1"
#ENV2 = "value2"

[[tunnels]]
#tunnel_type = "minecraft-java"
#id = "9e0a3886-8b6d-403a-9755-1d67987eb440"
name = "YesheyTunnel2"
proto = "both"
port_count = 2
local = 25565

#[[tunnels]]
#id = "0bb170d8-a949-49a5-a747-5ecac885c441"
#name = "ssh-tunnel"
#proto = "tcp"
#port_count = 1
#local = 9999

special_lan = true